export const ADD_TAB_NAV_ITEM = 'ADD_TAB_NAV_ITEM'
export const REMOVE_TAB_NAV_ITEM = 'REMOVE_TAB_NAV_ITEM'
export const SET_CURRENT_PAGE_CLASS = 'SET_CURRENT_PAGE_CLASS'
export const SET_CURRENT_ORG = 'SET_CURRENT_ORG'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_CURRENT_MENU = 'SET_CURRENT_MENU'
export const SET_CURRENT_MENU_POS = 'SET_CURRENT_MENU_POS'
export const SET_VIP_INFO = 'SET_VIP_INFO'
export const SET_CREDIT_INFO = 'SET_CREDIT_INFO'
export const SET_CARD_INFO = 'SET_CARD_INFO'
export const SET_TRANS_CARD = 'SET_TRANS_CARD'
export const SET_CARD_LIST_INFO = 'SET_CARD_LIST_INFO'
export const SET_VIP_STATUS = 'SET_VIP_STATUS'
export const SET_RULES_DETAIL = 'SET_RULES_DETAIL'
export const SET_RULES_ID = 'SET_RULES_ID'
export const SET_WX_TOKEN = 'SET_WX_TOKEN'
export const SET_BELONG_ORG = 'SET_BELONG_ORG'








